spring:
  application:
    name: DcmConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DebranaDutta/DcmConfigRepo
          clone-on-start: true

server:
  port: 8085

